### ISSUE TITLE
Curly Braces

### ISSUE THREAD

**Issue by albertlt** [monstrenyatko/ArduinoMqtt#10]
Hello. First of all, thanks a lot for publishing the library. Please mark this post as question and I'm sorry if this is a noob question (I am not from C background). While reading your example sketch: ConnectEsp8266WiFiClient.ino, I noticed the following codes in the loop() :

`// Start new MQTT connection`
    `MqttClient::ConnectResult connectResult;`
   ` // Connect`
   ` {`
        `MQTTPacket_connectData options = MQTTPacket_connectData_initializer;`
			`options.MQTTVersion = 4;`
			`options.clientID.cstring = (char*)MQTT_ID;`
			`options.cleansession = true;`
			`options.keepAliveInterval = 15; // 15 seconds`
			`MqttClient::Error::type rc = mqtt->connect(options, connectResult);`
			`if (rc != MqttClient::Error::SUCCESS) {`
				`LOG_PRINTFLN("Connection error: %i", rc);`
				`return;`
			`}`
		`}`

I don't understand what is the meaning of curly braces "without parent" right just below //Connect. As per my understanding, curly braces normally encapsulate code inside if, loop, function declaration, etc. But in your example, it's just simply a pair of curly braces. If I remove the curly braces, the code will also compile fine. I must be missing something, please enlighten me.

Also I am planning to use qos 2. I noticed in the description that this library support "simplified" qos 2. What does it mean? Lastly, is this library stable for production use?

**Comment by albertlt** [comment]
Oh I see, thanks a lot for the explanation. Lastly, is the library stable for production use?

**Comment by monstrenyatko** [comment]
@albertlt 
The library is stable enough. I am using it for my pet projects. Messages encoder/decoder is based on [Eclipse Paho MQTTPacket](https://github.com/eclipse/paho.mqtt.embedded-c/tree/master/MQTTPacket) library that is very well tested.

If you find an issue please report.

**Comment by albertlt** [comment]
Great. Will do. Thanks a lot =)

**Comment by monstrenyatko** [comment]
@albertlt 
No problem :-) Let me know if you have questions.

**Comment by albertlt** [comment]
Hello again. I was trying to use this library for communicating with Home Assistant embedded MQTT server. While I could see from Serial that the command was sent correctly, it was not read by Home Assistant. I tried Qos 1 on the PUB and I could see ACK received in terminal, proving that server was responding. However, there might be problem with the topic or payload as receive was not responding. I then tried the PubSubClient by Knolleary and it worked. The Home Assistant server is responding to the client. What could be wrong here?

**Comment by monstrenyatko** [comment]
@albertlt 
It could be a problem with your broker.
Does the broker support `QoS2`?
Does the [pubsubclient](https://github.com/knolleary/pubsubclient) publishes with `QoS2`?
Could you please try with `test.mosquitto.org` broker and share logs with `MQTT_LOG_ENABLED` defined to `1`.
If `QoS1` publish works fine, that means the communication with the broker is definitely OK.

**Comment by monstrenyatko** [comment]
@albertlt 
Did you try `QoS2` publishing with `test.mosquitto.org` broker?
In my case, it works well.
