### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by DavidMR91** [monstrenyatko/ArduinoMqtt#24]
Hello, when this line: 

LOG_PRINTFLN("Connection error: %i", rc);

is rturning:
Connection error: %i-5
or
Connection error: %i-6

what do these errors mean?
What is the meaning of the other numbers it can return?

**Comment by monstrenyatko** [comment]
It just prints the value of the `rc`.
I assume you are about the `rc` of the connect call: `Error::type connect(const MQTTPacket_connectData& connectOptions, ConnectResult& result)` call.

See enum for all possible `Error::type` values: [MqttClient.h#L200](https://github.com/monstrenyatko/ArduinoMqtt/blob/master/src/MqttClient.h#L200)
See the connect implementation to find more details: [MqttClient.h#L469](https://github.com/monstrenyatko/ArduinoMqtt/blob/master/src/MqttClient.h#L469)
