### ISSUE TITLE
support LastWill Message

### ISSUE THREAD

**Issue by tarzan115** [monstrenyatko/ArduinoMqtt#3]
I wonder if your library has support Lastwill message?

**Comment by monstrenyatko** [comment]
@tarzan115 
It should work. Please take a look on `MqttClient::connect`.
The first parameter `MQTTPacket_connectData` allows you to specify `MQTT` `CONNECT` message options.
I believe you are looking for `MQTTPacket_connectData::will` that contains all parameters related to `LWT` and `MQTTPacket_connectData::willFlag` that must be set to `true` for enabling of the `LWT`.

**Comment by tarzan115** [comment]
Sorry, my mistake. I got it. thank you so much.
