### ISSUE TITLE
MqttClient::Network implementation

### ISSUE THREAD

**Issue by svebert** [monstrenyatko/ArduinoMqtt#30]
Is there an example for the implementation of the MqttClient::Network class for a SIM chip with AT commands (any SIM7600, or SIM800)?
What exactly does the functions read and write have to do?

**Comment by svebert** [comment]
I found a better(?) solution for my application. Actually, I am using the SIM7600e chip. I found out, that it has a MQTT-Stack already built in. So it is not needed to implement the TCP/MQTT on arduino for yourself. You can easily use AT-Commands for connecting, publishing and subscribing to a MQTT server.

This: https://simcom.ee/documents/SIM7X00/SIM7500_SIM7600_SIM7800%20Series_MQTT_AT%20Command%20Manual_V1.00.pdf
and that:
https://github.com/elementzonline/Arduino-Sample-Codes/blob/master/SIM7600/Sim7600_MQTT/Sim7600_MQTT.ino
did help me a lot

**Comment by monstrenyatko** [comment]
Hi @svebert, I do not have experience with SIM chips.

The network class should provide the read/write implementation to receive/send MQTT packets (wo TCP layer) from/to the broker. I have a few implementation examples in the project, see **extras/examples** and **examples/PubSub**.
